### ISSUE TITLE
Misleading data source in readme

### ISSUE THREAD

**Issue by montanaflynn** [paul-em/covid-19-curves#1]
> Data is loaded from the [Website of the World Health Organization](https://www.who.int/emergencies/diseases/novel-coronavirus-2019/situation-reports/) via the CSV file provided.

I couldn't find any CSV on the WHO website. Looking at the source the data is actually pulled from:

```js
const url = 'https://covid.ourworldindata.org/data/full_data.csv';
```

**Comment by paul-em** [comment]
Hi! Thanks for checking on this. I updated this since then a couple of times. Our World In Data was using the data from WHO. However I updated to use data from John Hopkins instead now, because it also includes the recovered cases, which makes more sense for the curves.
