### ISSUE TITLE
include predictive modeling id 1757 #wirvsvirus

### ISSUE THREAD

**Issue by chicotobi** [paul-em/covid-19-curves#4]
As proposed in the hackathon challenge. I'm a mathematician working in pharma/diagnostics, didn't find another way to reach you than opening an issue.

**Comment by paul-em** [comment]
Hi! Thanks for doing so, seems quite chaotic. I opened a hangout: https://hangouts.google.com/call/KpYMbqNgMQuS-27jcYOxAEEI
